CBT/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using CBT.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CBT.Controllers
{
    public class EventController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private RoleManager<IdentityRole> _roleManager;
        public ApplicationDbContext db = new ApplicationDbContext();
        public ApplicationUser CurrentUser { get; set; }

        public EventController()
        {
        }

        public EventController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public RoleManager<IdentityRole> RoleManager
        {
            get
            {
                return _roleManager ?? new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            }
            private set
            {
                _roleManager = value;
            }
        }

        [Authorize(Roles = "Администратор мероприятия")]
        // GET: Event
        [HttpGet]
        public ActionResult Index()
        {
            List<EventUserRelationship> EventUser = new List<EventUserRelationship>();
            EventUser.AddRange(this.db.EventUserRelationship);
            this.ViewBag.EventUser = EventUser;
            List<Field> fields = new List<Field>();
            fields.AddRange(this.db.Fields);
            this.ViewBag.Fields = fields;
            List<Event> events = new List<Event>();
            ApplicationUser cur_user = this.db.Users.Find(this.User.Identity.GetUserId());
            foreach (Event e in this.db.Events)
            {
                if (cur_user.CreatedEvents.Contains(e))
                {
                    events.Add(e);
                }
            }
            this.ViewBag.Admin = this.User.IsInRole("Администратор мероприятия");
            this.ViewBag.IsAuthenticated = false;
            this.ViewBag.UserId = this.User.Identity.GetUserId();
            this.ViewBag.Events = events;
            return View();
        }

        // POST: Event/Create
        [HttpPost]
        [Authorize(Roles = "Администратор мероприятия")]
        public ActionResult Create(Event model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Event res_event = new Event { Title = model.Title, MaxUsers = model.MaxUsers, SignedUsersCount = model.SignedUsersCount, Fields = model.Fields };
                    List<Field> fields = model.Fields.ToList();
                    foreach (Field item in fields)
                    {

                        item.Event = res_event;
                        res_event.Fields.Add(item);
                    }

                    //res_event.UserId = this.User.Identity.GetUserId();
                    this.db.Events.Add(res_event);
                    ApplicationUser cur_user = this.db.Users.Find(this.User.Identity.GetUserId());
                    cur_user.CreatedEvents.Add(res_event);
                    this.db.SaveChanges();
                }

                // Появление этого сообщения означает наличие ошибки; повторное отображение формы
                //return View(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Title = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

CBT/Controllers/HomeController.cs
using CBT.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CBT.Controllers
{
    public class HomeController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();
        public ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? this.HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            this.ViewBag.Admin = this.User.IsInRole("Администратор мероприятия");
            this.ViewBag.IsAuthenticated = this.User.Identity.IsAuthenticated;
            this.ViewBag.UserId = this.User.Identity.GetUserId();
            this.ViewBag.Events = this.db.Events;
            List<EventUserRelationship> EventUser = new List<EventUserRelationship>();
            EventUser.AddRange(this.db.EventUserRelationship);
            this.ViewBag.EventUser = EventUser;
            List<Field> fields = new List<Field>();
            fields.AddRange(this.db.Fields);
            this.ViewBag.Fields = fields;
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Web-приложение Event planning для получения работы в компании Центр банковских технологий.";

            return View();
        }

        [HttpPost]
        public ActionResult SignProjectAsync(string id)
        {
            try
            {
                Event current_event = this.db.Events.Find(Convert.ToInt32(Request.Params[0]));
                var Sign = new EventUserRelationship { EventId = current_event.Id, UserId = this.User.Identity.GetUserId() };
                if (this.db.EventUserRelationship.Any(e => e.EventId == Sign.EventId && e.UserId == Sign.UserId))
                {
                    this.db.EventUserRelationship.Remove(this.db.EventUserRelationship.Find(Sign.EventId, Sign.UserId));
                    if (current_event.SignedUsersCount > 0)
                    {
                        this.db.Events.Find(current_event.Id).SignedUsersCount -= 1;
                        this.db.Events.Find(current_event.Id).EventUsersSigned.Remove(Sign);
                        this.db.SaveChanges();
                    }
                }
                else
                {
                    this.db.EventUserRelationship.Add(Sign);
                    this.db.SaveChanges();
                    if (this.db.Events.Any(p => p.EventUsersSigned.Any(f => f.EventId == current_event.Id)))
                    {
                        if (current_event.MaxUsers != current_event.SignedUsersCount)
                        {
                            this.db.Events.Find(current_event.Id).SignedUsersCount += 1;
                            this.db.Events.Find(current_event.Id).EventUsersSigned.Add(Sign);
                            this.db.SaveChanges();
                        }
                    }
                }
                this.ViewBag.IsAuthenticated = this.User.Identity.IsAuthenticated;
                this.ViewBag.UserId = this.User.Identity.GetUserId();
                List<EventUserRelationship> EventUser = new List<EventUserRelationship>();
                EventUser.AddRange(this.db.EventUserRelationship);
                this.ViewBag.EventUser = EventUser;
                this.ViewBag.Fields = this.db.Fields;

                return PartialView("EventPartialView", current_event);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return PartialView();
            }
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Мои контакты";

            return View();
        }
    }
}

CBT/Views/Home/About.cshtml
@{
    ViewBag.Title = "О программе";
}
<h2>@ViewBag.Title:</h2>
<h3>@ViewBag.Message</h3>

<p>Есть административная и пользовательская части.</p>

<table>
    <tr>
        <td>
            <h4>Функции административной части:</h4>
        </td>
        <td>
            <h4> Функции пользовательской части:</h4>
        </td>
    </tr>
    <tr>
        <td>
            <ul>
                <li>Пользователь создаёт мероприятие произвольного типа с произвольным набором полей на определённую дату и время</li>
                <li>
                    Например:
                    <ul>
                        <li>Наименование: тестовое мероприятие 1</li>
                        <li>Тема: Спорт</li>
                        <li>Местоположение: Кальварийская 7</li>
                    </ul>
                </li>
                <li>
                    Или:
                    <ul>
                        <li>Наименование: тестовое мероприятие 2</li>
                        <li>Дресс-код: обязателен</li>
                        <li>Тема: Музыка</li>
                        <li>Подтема: Рок</li>
                        <li>Подтема: Классическая музыка</li>
                        <li>Участники: Певцы</li>
                        <li>Деревня: Иваново</li>
                    </ul>
                </li>
            </ul>
        </td>
        <td>
            <ul>
                <li>Пользователь может зарегистрироваться на данное мероприятие</li>
            </ul>
        </td>
    </tr>
</table>

CBT/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакт";
}
<h3>@ViewBag.Message</h3>

<address>
    Андрей Чаевский<br />
    Минск, ул. Белорусская, 21<br />
    andreichayeuski@gmail.com<br />
    <abbr title="Phone">P:</abbr>
    +375336345353
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:eventplanning_chayeuski@mail.ru">eventplanning_chayeuski@mail.ru</a><br />
</address>

CBT/Views/Home/Index.cshtml
@model CBT.Models.Event
@{
    ViewBag.Title = "Event Planning";
    ViewBag.count = 0;
}

<div class="jumbotron">
    <h1>Event Planning</h1>
    <p class="lead">Event planning - приложение для создания и просмотра мероприятий</p>
    @if (!ViewBag.IsAuthenticated)
    {
        @Html.ActionLink("Зарегистрироваться", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "btn btn-primary btn-lg" })
    }
</div>
@if (ViewBag.Admin)
{
    <div class="active">
        @Html.ActionLink("Создать новое мероприятие", "Index", "Event", routeValues: null, htmlAttributes: new { id = "createLink", @class = "btn btn-primary btn-lg" })
    </div>
}
<div class="row">
    <h2>Текущие мероприятия</h2>
    <table>
        @foreach (CBT.Models.Event p in ViewBag.Events)
        {
            @Html.Partial("EventPartialView", p)
            ViewBag.count += 1;
        }
    </table>
</div>
@section Scripts {
    <script>
        function FuncOnClick(counter) {
            var str_sign = '#sign' + counter;
            var str_div = '#div_sign' + counter;
            $.ajax({
                type: "POST",
                url: '/Home/SignProjectAsync',
                data: $(str_sign).val(),
                success: function (data) {
                    $(str_div).replaceWith(data);
                }
            });
        }
    </script>
}